# Generated by Django 2.0.5 on 2018-05-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteA', models.IntegerField(default=0)),
                ('voteB', models.IntegerField(default=0)),
                ('choiceA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceA', to='polls.Choice')),
                ('choiceB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceB', to='polls.Choice')),
            ],
        ),
    ]
