# Generated by Django 2.0.5 on 2018-05-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
