# Generated by Django 2.0.5 on 2018-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
    ]
