# Generated by Django 2.0.5 on 2018-05-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_win_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='win_against',
            field=models.ManyToManyField(related_name='_choice_win_against_+', to='polls.Choice'),
        ),
    ]
