# Generated by Django 2.0.5 on 2018-05-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice_win_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='win_against',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
    ]
