# Generated by Django 2.0.5 on 2018-05-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180513_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='win_against',
            new_name='win_against_m2m',
        ),
    ]
