# Generated by Django 2.0.5 on 2018-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_choice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
