# Generated by Django 2.0.5 on 2018-05-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
